networks:
  inception:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    expose:
      - "3306"
    restart: on-failure

  nginx:
    container_name: nginx
    networks:
      - inception
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    networks:
      - inception
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    expose:
      - "9000"
    restart: on-failure



volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind' # Les Bind Mounts sont des volumes qui se montent sur un chemin d'accès à l'hôte, et ils peuvent être modifiés par d'autres processus en dehors de docker.
      device: '/home/ajakubcz/data/wordpress' #Ou stocker le dossier sur votre ordinateur en local
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ajakubcz/data/mariadb'
